import React from "react";
import {
  View,
  Text,
  StyleSheet,
  StatusBar,
  ScrollView,
  Dimensions,
  Image,
} from "react-native";
import {
  Ionicons,
  MaterialCommunityIcons,
  Feather,
} from "@expo/vector-icons";

const { width } = Dimensions.get("window");

export default function PropertyReport({ project, projectDetails }) {
  const currentDate = new Date().toLocaleDateString('en-GB');
  
  return (
    <View style={styles.container}>
      {/* Header */}
      <View style={styles.header}>
        <View>
          <Text style={styles.headerTitle}>
            Property report generated by Arpit Aryan Gupta on {currentDate}
          </Text>
        </View>
        <View style={styles.logoWrap}>
          <View style={styles.logoContainer}>
            <View style={styles.logoCircle}>
              <Text style={styles.logoL}>L</Text>
            </View>
            <Text style={styles.logoText}>LIYANTIS</Text>
          </View>
        </View>
      </View>

      <View style={styles.divider} />

      {/* Property Name */}
      <View style={styles.centerBlock}>
        <Text style={styles.propertyName}>
          {project?.projectName || "The Weave"}, {project?.location || "JVC"} by {project?.developer || "Al Ghurair"}
        </Text>
        <Text style={styles.builder}>Ð</Text>
        <Text style={styles.price}>
          {projectDetails?.price?.currency || "AED"} {(project?.price || 1197013).toLocaleString()}.00
        </Text>
      </View>

      {/* Rating */}
      <View style={styles.ratingRow}>
        <View style={styles.ratingContainer}>
          <View style={styles.ratingCircleBackground} />
          <View style={styles.ratingCircleProgress} />
          <View style={styles.ratingCircleInner}>
            <Text style={styles.ratingText}>{projectDetails?.rating || "7.5"}</Text>
          </View>
        </View>
        <Text style={styles.ratingDesc}>
          The final project rating is an aggregate score calculated from all the
          individual parameters assessed by the agent.
        </Text>
      </View>

      {/* Property Details */}
      <Text style={styles.sectionTitle}>Property details</Text>
      <View style={styles.detailsRow}>
        <Detail
          icon={<MaterialCommunityIcons name="bed" size={16} color="#9CA3AF" />}
          label={`${project?.bedrooms || 1} Bedroom`}
          sub="776 ft²"
        />
        <Detail
          icon={<Feather name="home" size={16} color="#9CA3AF" />}
          label="Apartment"
          sub={project?.status || "Off-Plan"}
        />
        <Detail
          icon={<Ionicons name="location-outline" size={16} color="#9CA3AF" />}
          label={project?.location || "JVC"}
          sub="Dubai"
        />
      </View>

      {/* Exit Strategies */}
      <View style={styles.card}>
        <Text style={styles.sectionTitle}>Exit Strategies</Text>
        <View style={styles.exitTabs}>
          <Text style={styles.exitTabActive}>STP</Text>
          <Text style={styles.exitTab}>MTP</Text>
          <Text style={styles.exitTab}>LTP</Text>
        </View>
        <View style={styles.table}>
          <TableRow
            title=""
            moderate="Moderate"
            cons="Conservative"
            opt="Optimistic"
          />
          <TableRow
            title="STP"
            moderate={projectDetails?.exitStrategies?.stp?.moderate?.percent || "25.46%"}
            moderateAmt={projectDetails?.exitStrategies?.stp?.moderate?.val || "AED 137.24k"}
            cons={projectDetails?.exitStrategies?.stp?.conservative?.percent || "7.87%"}
            consAmt={projectDetails?.exitStrategies?.stp?.conservative?.val || "AED 42.42k"}
            opt={projectDetails?.exitStrategies?.stp?.optimistic?.percent || "34.46%"}
            optAmt={projectDetails?.exitStrategies?.stp?.optimistic?.val || "AED 185.75k"}
          />
          <TableRow
            title="MTP"
            moderate={projectDetails?.exitStrategies?.mtp?.moderate?.percent || "25.46%"}
            moderateAmt={projectDetails?.exitStrategies?.mtp?.moderate?.val || "AED 137.24k"}
            cons={projectDetails?.exitStrategies?.mtp?.conservative?.percent || "7.87%"}
            consAmt={projectDetails?.exitStrategies?.mtp?.conservative?.val || "AED 42.42k"}
            opt={projectDetails?.exitStrategies?.mtp?.optimistic?.percent || "34.46%"}
            optAmt={projectDetails?.exitStrategies?.mtp?.optimistic?.val || "AED 185.75k"}
          />
          <TableRow
            title="LTP"
            moderate={projectDetails?.exitStrategies?.ltp?.moderate?.percent || "117.72%"}
            moderateAmt={projectDetails?.exitStrategies?.ltp?.moderate?.val || "AED 137.24k"}
            cons={projectDetails?.exitStrategies?.ltp?.conservative?.percent || "49.18%"}
            consAmt={projectDetails?.exitStrategies?.ltp?.conservative?.val || "AED 42.42k"}
            opt={projectDetails?.exitStrategies?.ltp?.optimistic?.percent || "160.32%"}
            optAmt={projectDetails?.exitStrategies?.ltp?.optimistic?.val || "AED 185.75k"}
            last
          />
        </View>
      </View>
    </View>
  );
}

/* ---------- Components ---------- */
const Detail = ({ icon, label, sub }) => (
  <View style={styles.detailItem}>
    {icon && (
      <View style={{ marginBottom: 8 }}>
        {icon}
      </View>
    )}
    <Text style={styles.detailValue}>{label}</Text>
    {sub && <Text style={styles.detailSub}>{sub}</Text>}
  </View>
);

const TableRow = ({
  title,
  moderate,
  moderateAmt,
  cons,
  consAmt,
  opt,
  optAmt,
  last,
}) => (
  <View style={[styles.tableRow, last && { borderBottomWidth: 0 }]}>
    <View style={styles.tableLeft}>
      <Text style={styles.tableTitle}>{title}</Text>
    </View>
    <View style={styles.tableCol}>
      <Text style={styles.percent}>{moderate}</Text>
      {moderateAmt && <Text style={styles.amount}>{moderateAmt}</Text>}
    </View>
    <View style={styles.tableCol}>
      <Text style={styles.percent}>{cons}</Text>
      {consAmt && <Text style={styles.amount}>{consAmt}</Text>}
    </View>
    <View style={styles.tableCol}>
      <Text style={styles.percent}>{opt}</Text>
      {optAmt && <Text style={styles.amount}>{optAmt}</Text>}
    </View>
  </View>
);

/* ---------- Styles ---------- */
const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#0F1115",
    paddingHorizontal: 20,
  },
  header: {
    marginTop: 0,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  headerTitle: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "600",
  },
  headerSub: {
    color: "#9CA3AF",
    fontSize: 10,
    marginTop: 4,
  },
  logoWrap: {
    justifyContent: "center",
    alignItems: "center",
  },
  logoContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  logoCircle: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: "#FF6B00",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 6,
  },
  logoL: {
    color: "#FFFFFF",
    fontWeight: "700",
  },
  logoText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
  },
  divider: {
    height: 1,
    marginVertical: 20,
    borderTopWidth: 1,
    borderTopColor: "#F5F5F5",
    borderStyle: "dashed",
  },
  centerBlock: {
    alignItems: "center",
  },
  propertyName: {
    color: "#F1FE74",
    fontSize: 22,
    fontWeight: "600",
  },
  builder: {
    color: "#9CA3AF",
    fontSize: 13,
    marginTop: 4,
  },
  price: {
    color: "#FFFFFF",
    fontSize: 26,
    fontWeight: "700",
    marginTop: 16,
  },
  ratingRow: {
    flexDirection: "row",
    marginTop: 30,
    alignItems: "center",
  },
  ratingContainer: {
    width: 54,
    height: 54,
    marginRight: 16,
    position: "relative",
    justifyContent: "center",
    alignItems: "center",
  },
  ratingCircleBackground: {
    position: "absolute",
    width: 54,
    height: 54,
    borderRadius: 27,
    borderWidth: 4,
    borderColor: "#5E6272",
  },
  ratingCircleProgress: {
    position: "absolute",
    width: 54,
    height: 54,
    borderRadius: 27,
    borderWidth: 4,
    borderColor: "transparent",
    borderTopColor: "#F1FE74",
    borderRightColor: "#F1FE74",
    borderBottomColor: "#F1FE74",
    transform: [{ rotate: "135deg" }],
  },
  ratingCircleInner: {
    width: 46,
    height: 46,
    borderRadius: 23,
    backgroundColor: "#0F1115",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1,
  },
  ratingCircle: {
    width: 54,
    height: 54,
    borderRadius: 27,
    borderWidth: 4,
    borderColor: "#F1FE74",
    justifyContent: "center",
    alignItems: "center",
    marginRight: 16,
  },
  ratingText: {
    color: "#FFFFFF",
    fontWeight: "700",
    fontSize: 16,
  },
  ratingDesc: {
    color: "#F5F5F5",
    fontSize: 13,
    flex: 1,
    lineHeight: 18,
  },
  sectionTitle: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "600",
    marginTop: 30,
    marginBottom: 16,
  },
  detailsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  detailItem: {
    alignItems: "center",
    flex: 1,
  },
  detailValue: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "400",
  },
  detailSub: {
    color: "#9CA3AF",
    fontSize: 11,
    marginTop: 2,
  },
  card: {
    backgroundColor: "#171A20",
    borderRadius: 14,
    marginTop: 30,
    padding: 16,
  },
  exitTabs: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  exitTab: {
    color: "#FFFFFF",
    fontSize: 13,
  },
  exitTabActive: {
    color: "#F1FE74",
    fontWeight: "600",
  },
  table: {
    borderTopWidth: 1,
    borderTopColor: "#2A2E35",
  },
  tableRow: {
    flexDirection: "row",
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: "#2A2E35",
  },
  tableLeft: {
    flex: 2,
  },
  tableTitle: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "500",
  },
  tableCol: {
    flex: 1,
    alignItems: "flex-end",
  },
  percent: {
    color: "#FFFFFF",
    fontSize: 13,
    fontWeight: "600",
  },
  amount: {
    color: "#9CA3AF",
    fontSize: 12,
    marginTop: 4,
  },
});